modLoader="javafml"
loaderVersion="[52,)"
license="MIT"

[[mods]]
    modId="smarthopper"
    version="1.0.0"
    displayName="Smart Hopper"
    authors="Javier Delgado"
    description='''Tolva inteligente con sistema de filtrado.'''

[[dependencies.smarthopper]]
    modId="forge"
    mandatory=true
    versionRange="[52,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.smarthopper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"